### ISSUE TITLE
Correct proto generation with telescope for regen ledger & move location to regen's github

### ISSUE THREAD

**Issue by haveanicedavid** [regen-network/groups-ui#33] opened 2023-04-15 00:16 UTC
There's currently an issue with the newly generated helper library (https://github.com/haveanicedavid/regen-ts) that's preventing regen proto files from properly being parsed by telescope. This might be related to protobufjs, in which case we should file a ticket, but we need to do a bit more digging to know what's going on.

Once we can successfully generate regen types, we should move the code to live under the regen-network github

![image.png](https://images.zenhubusercontent.com/58d5565151aa2c3057796a58/9a1590e7-3ea5-4adc-8cf6-30baf4516f09)

**Comment by ryanchristo** [comment] 2023-05-12 15:53
This issue was caused by `doc.proto`. We don't need to generate anything from this file (only used to document and generate documentation on buf registry). Simply removing it from all regen modules resolves the first error.

Another error followed with how we write query rpc methods. From my experience, we only need the query messages, not the rpc methods, so simply removing the query service resolves the issue.

In general, we are copying over more protobuf than needed. We really only need types, messages, and queries. For messages and queries, we don't need msg service and query service. We might need to open an issue in telescope/protobufjs to handle or ignore the two cases encountered with the regen proto files as these files are valid proto but as a short-term solution, we can simply remove the code that is causing the errors.

**Comment by ryanchristo** [comment] 2023-05-12 15:57
I'm going to open a pull request in regen-js with a working version. We are essentially using telescope for api v1 (we have yet to do a major release for the api package). I'm going to add it as a separate package for the time being so we can develop both in parallel and continue to do minor releases for the existing api package until we are ready to migrate.

**Comment by clevinson** [comment] 2023-05-18 18:11
This can be closed once regen-js#68 gets merged

**Closed** 2023-05-18 23:09 UTC
Labels: enhancement
